# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hotpot',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/hotpot',
                'lib_path': 'hotpot'},
  'syms': {'hotpot.core': {'hotpot.core.foo': ('core.html#foo', 'hotpot/core.py')}}}
