# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hot-pot',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/hot-pot',
                'lib_path': 'hot_pot'},
  'syms': { 'hot_pot.template': { 'hot_pot.template._cu_window_sum_2d': ('template.html#_cu_window_sum_2d', 'hot_pot/template.py'),
                                  'hot_pot.template._window_sum_2d': ('template.html#_window_sum_2d', 'hot_pot/template.py'),
                                  'hot_pot.template.cu_match_template': ('template.html#cu_match_template', 'hot_pot/template.py'),
                                  'hot_pot.template.match_template': ('template.html#match_template', 'hot_pot/template.py')}}}
