# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sott',
                'doc_host': 'https://kanglcn.github.io',
                'git_url': 'https://github.com/kanglcn/sott',
                'lib_path': 'sott'},
  'syms': { 'sott.template': { 'sott.template._cu_window_sum_2d': ('template.html#_cu_window_sum_2d', 'sott/template.py'),
                               'sott.template._window_sum_2d': ('template.html#_window_sum_2d', 'sott/template.py'),
                               'sott.template.cu_match_template': ('template.html#cu_match_template', 'sott/template.py'),
                               'sott.template.match_template': ('template.html#match_template', 'sott/template.py')}}}
